Nilüfer'deki Kiralık Evler

In [1]:
import pandas as pd
import os
import numpy as np

In [2]:
dir(pd)

['ArrowDtype',
 'BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt8Dtype',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_built_with_meson',
 '_config',
 '_is_numpy_dev',
 '_libs',
 '_pandas_datetime_CAPI',
 '_pandas_parser_CAPI',
 '_testing',
 '_typing',
 '_version_meson',
 'annotations',
 'api',
 'array',
 'arrays',
 'bdate_range',
 'col',
 'compat',
 'concat',
 'core',
 'crosstab',
 'cut',
 'date_range',
 'describe_option',
 'errors',
 'eval',
 'factorize',
 'from_dummies',
 'get_dummies',
 'get_option',
 'infer_freq',
 'interval_range',
 'io',
 'isna',
 'isnull',
 'json_normalize',
 'lreshape',
 'melt',
 'merge',
 'merge_asof',
 'merge_ordered',
 'notna',
 'notnull',
 'offsets',
 'option_context',
 'options',
 'pandas',
 'period_range',
 'pivot',
 'pivot_table',
 'plotting',
 'qcut',
 'read_clipboard',
 'read_csv',
 'read_excel',
 'read_feather',
 'read_fwf',
 'read_hdf',
 'read_html',
 'read_iceberg',
 'read_json',
 'read_orc',
 'read_parquet',
 'read_pickle',
 'read_sas',
 'read_spss',
 'read_sql',
 'read_sql_query',
 'read_sql_table',
 'read_stata',
 'read_table',
 'read_xml',
 'reset_option',
 'set_eng_float_format',
 'set_option',
 'show_versions',
 'test',
 'testing',
 'timedelta_range',
 'to_datetime',
 'to_numeric',
 'to_pickle',
 'to_timedelta',
 'tseries',
 'unique',
 'util',
 'wide_to_long']

In [3]:
help(pd.read_csv)

Help on function read_csv in module pandas:

read_csv(filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]', *, sep: 'str | None | lib.NoDefault' = <no_default>, delimiter: 'str | None | lib.NoDefault' = None, header: "int | Sequence[int] | None | Literal['infer']" = 'infer', names: 'Sequence[Hashable] | None | lib.NoDefault' = <no_default>, index_col: 'IndexLabel | Literal[False] | None' = None, usecols: 'UsecolsArgType' = None, dtype: 'DtypeArg | None' = None, engine: 'CSVEngine | None' = None, converters: 'Mapping[HashableT, Callable] | None' = None, true_values: 'list | None' = None, false_values: 'list | None' = None, skipinitialspace: 'bool' = False, skiprows: 'list[int] | int | Callable[[Hashable], bool] | None' = None, skipfooter: 'int' = 0, nrows: 'int | None' = None, na_values: 'Hashable | Iterable[Hashable] | Mapping[Hashable, Iterable[Hashable]] | None' = None, keep_default_na: 'bool' = True, na_filter: 'bool' = True, skip_blank_lines: 'bool' = True, parse_dates: 'bool | Sequence[Hashable] | None' = None, date_format: 'str | dict[Hashable, str] | None' = None, dayfirst: 'bool' = False, cache_dates: 'bool' = True, iterator: 'bool' = False, chunksize: 'int | None' = None, compression: 'CompressionOptions' = 'infer', thousands: 'str | None' = None, decimal: 'str' = '.', lineterminator: 'str | None' = None, quotechar: 'str' = '"', quoting: 'int' = 0, doublequote: 'bool' = True, escapechar: 'str | None' = None, comment: 'str | None' = None, encoding: 'str | None' = None, encoding_errors: 'str | None' = 'strict', dialect: 'str | csv.Dialect | None' = None, on_bad_lines: 'str' = 'error', low_memory: 'bool' = True, memory_map: 'bool' = False, float_precision: "Literal['high', 'legacy', 'round_trip'] | None" = None, storage_options: 'StorageOptions | None' = None, dtype_backend: 'DtypeBackend | lib.NoDefault' = <no_default>) -> 'DataFrame | TextFileReader'
    Read a comma-separated values (csv) file into DataFrame.

    Also supports optionally iterating or breaking of the file
    into chunks.

    Additional help can be found in the online docs for
    `IO Tools <https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html>`_.

    Parameters
    ----------
    filepath_or_buffer : str, path object or file-like object
        Any valid string path is acceptable. The string could be a URL. Valid
        URL schemes include http, ftp, s3, gs, and file. For file URLs, a host is
        expected. A local file could be: file://localhost/path/to/table.csv.

        If you want to pass in a path object, pandas accepts any ``os.PathLike``.

        By file-like object, we refer to objects with a ``read()`` method, such as
        a file handle (e.g. via builtin ``open`` function) or ``StringIO``.
    sep : str, default ','
        Character or regex pattern to treat as the delimiter. If ``sep=None``, the
        C engine cannot automatically detect
        the separator, but the Python parsing engine can, meaning the latter will
        be used and automatically detect the separator from only the first valid
        row of the file by Python's builtin sniffer tool, ``csv.Sniffer``.
        In addition, separators longer than 1 character and different from
        ``'\s+'`` will be interpreted as regular expressions and will also force
        the use of the Python parsing engine. Note that regex delimiters are prone
        to ignoring quoted data. Regex example: ``'\r\t'``.
    delimiter : str, optional
        Alias for ``sep``.
    header : int, Sequence of int, 'infer' or None, default 'infer'
        Row number(s) containing column labels and marking the start of the
        data (zero-indexed). Default behavior is to infer the column names:
        if no ``names``
        are passed the behavior is identical to ``header=0`` and column
        names are inferred from the first line of the file, if column
        names are passed explicitly to ``names`` then the behavior is identical to
        ``header=None``. Explicitly pass ``header=0`` to be able to
        replace existing names. The header can be a list of integers that
        specify row locations for a :class:`~pandas.MultiIndex` on the columns
        e.g. ``[0, 1, 3]``. Intervening rows that are not specified will be
        skipped (e.g. 2 in this example is skipped). Note that this
        parameter ignores commented lines and empty lines if
        ``skip_blank_lines=True``, so ``header=0`` denotes the first line of
        data rather than the first line of the file.

        When inferred from the file contents, headers are kept distinct from
        each other by renaming duplicate names with a numeric suffix of the form
        ``".{{count}}"`` starting from 1, e.g. ``"foo"`` and ``"foo.1"``.
        Empty headers are named ``"Unnamed: {{i}}"`` or ``
        "Unnamed: {{i}}_level_{{level}}"``
        in the case of MultiIndex columns.
    names : Sequence of Hashable, optional
        Sequence of column labels to apply. If the file contains a header row,
        then you should explicitly pass ``header=0`` to override the column names.
        Duplicates in this list are not allowed.
    index_col : Hashable, Sequence of Hashable or False, optional
        Column(s) to use as row label(s), denoted either by column labels or column
        indices.  If a sequence of labels or indices is given,
        :class:`~pandas.MultiIndex`
        will be formed for the row labels.

        Note: ``index_col=False`` can be used to force pandas to *not* use the first
        column as the index, e.g., when you have a malformed file with delimiters at
        the end of each line.
    usecols : Sequence of Hashable or Callable, optional
        Subset of columns to select, denoted either
        by column labels or column indices.
        If list-like, all elements must either
        be positional (i.e. integer indices into the document columns) or strings
        that correspond to column names provided either by the user in ``names`` or
        inferred from the document header row(s).
        If ``names`` are given, the document
        header row(s) are not taken into account. For example, a valid list-like
        ``usecols`` parameter would be ``[0, 1, 2]`` or ``['foo', 'bar', 'baz']``.
        Element order is ignored, so ``usecols=[0, 1]`` is the same as ``[1, 0]``.
        To instantiate a :class:`~pandas.DataFrame` from ``data`` with element order
        preserved use ``pd.read_csv(data, usecols=['foo', 'bar'])[['foo', 'bar']]``
        for columns in ``['foo', 'bar']`` order or
        ``pd.read_csv(data, usecols=['foo', 'bar'])[['bar', 'foo']]``
        for ``['bar', 'foo']`` order.

        If callable, the callable function will be evaluated against the column
        names, returning names where the callable function evaluates to ``True``. An
        example of a valid callable argument would be ``lambda x: x.upper() in
        ['AAA', 'BBB', 'DDD']``. Using this parameter results in much faster
        parsing time and lower memory usage.
    dtype : dtype or dict of {{Hashable : dtype}}, optional
        Data type(s) to apply to either the whole dataset or individual columns.
        E.g., ``{{'a': np.float64, 'b': np.int32, 'c': 'Int64'}}``
        Use ``str`` or ``object`` together with suitable ``na_values`` settings
        to preserve and not interpret ``dtype``.
        If ``converters`` are specified, they will be applied INSTEAD
        of ``dtype`` conversion. Specify a ``defaultdict`` as input where
        the default determines the ``dtype``
        of the columns which are not explicitly
        listed.
    engine : {{'c', 'python', 'pyarrow'}}, optional
        Parser engine to use. The C and pyarrow engines are faster,
        while the python engine
        is currently more feature-complete. Multithreading
        is currently only supported by
        the pyarrow engine. Some features of the "pyarrow" engine
        are unsupported or may not work correctly.
    converters : dict of {{Hashable : Callable}}, optional
        Functions for converting values in specified columns. Keys can either
        be column labels or column indices.
    true_values : list, optional
        Values to consider as ``True`` in addition
        to case-insensitive variants of 'True'.
    false_values : list, optional
        Values to consider as ``False`` in addition to case-insensitive
        variants of 'False'.
    skipinitialspace : bool, default False
        Skip spaces after delimiter.
    skiprows : int, list of int or Callable, optional
        Line numbers to skip (0-indexed) or number of lines to skip (``int``)
        at the start of the file.

        If callable, the callable function will be evaluated against the row
        indices, returning ``True`` if the row should be skipped and ``False``
        otherwise.
        An example of a valid callable argument would be ``lambda x: x in [0, 2]``.
    skipfooter : int, default 0
        Number of lines at bottom of file to skip (Unsupported with ``engine='c'``).
    nrows : int, optional
        Number of rows of file to read. Useful for reading pieces of large files.
        Refers to the number of data rows in the returned DataFrame, excluding:

        * The header row containing column names.
        * Rows before the header row, if ``header=1`` or larger.

        Example usage:

        * To read the first 999,999 (non-header) rows:
          ``read_csv(..., nrows=999999)``

        * To read rows 1,000,000 through 1,999,999:
          ``read_csv(..., skiprows=1000000, nrows=999999)``

    na_values : Hashable, Iterable of Hashable or dict of {{Hashable : Iterable}},
        optional
        Additional strings to recognize as ``NA``/``NaN``. If ``dict``
        passed, specific
        per-column ``NA`` values.  By default the following values
        are interpreted as
        ``NaN``: empty string, "NaN", "N/A", "NULL", and other common
        representations of missing data.
    keep_default_na : bool, default True
        Whether or not to include the default ``NaN`` values when parsing the data.
        Depending on whether ``na_values`` is passed in, the behavior is as follows:

        * If ``keep_default_na`` is ``True``, and ``na_values``
          are specified, ``na_values``
          is appended to the default ``NaN`` values used for parsing.
        * If ``keep_default_na`` is ``True``, and ``na_values`` are not specified, only
          the default ``NaN`` values are used for parsing.
        * If ``keep_default_na`` is ``False``, and ``na_values`` are specified, only
          the ``NaN`` values specified ``na_values`` are used for parsing.
        * If ``keep_default_na`` is ``False``, and ``na_values`` are not specified, no
          strings will be parsed as ``NaN``.

        Note that if ``na_filter`` is passed in as ``False``,
        the ``keep_default_na`` and
        ``na_values`` parameters will be ignored.
    na_filter : bool, default True
        Detect missing value markers (empty strings and the value of ``na_values``). In
        data without any ``NA`` values, passing ``na_filter=False`` can improve the
        performance of reading a large file.
    skip_blank_lines : bool, default True
        If ``True``, skip over blank lines rather than interpreting as ``NaN`` values.
    parse_dates : bool, None, list of Hashable, default None
        The behavior is as follows:

        * ``bool``. If ``True`` -> try parsing the index.
        * ``None``. Behaves like ``True`` if ``date_format`` is specified.
        * ``list`` of ``int`` or names.
          e.g. If ``[1, 2, 3]`` -> try parsing columns 1, 2, 3
          each as a separate date column.

        If a column or index cannot be represented as an array of ``datetime``,
        say because of an unparsable value or a mixture of timezones, the column
        or index will be returned unaltered as an ``object`` data type. For
        non-standard ``datetime`` parsing, use :func:`~pandas.to_datetime` after
        :func:`~pandas.read_csv`.

        Note: A fast-path exists for iso8601-formatted dates.
    date_format : str or dict of column -> format, optional
        Format to use for parsing dates and/or times when
        used in conjunction with ``parse_dates``.
        The strftime to parse time, e.g. :const:`"%d/%m/%Y"`. See
        `strftime documentation
        <https://docs.python.org/3/library/datetime.html
        #strftime-and-strptime-behavior>`_ for more information on choices, though
        note that :const:`"%f"`` will parse all the way up to nanoseconds.
        You can also pass:

        - "ISO8601", to parse any `ISO8601 <https://en.wikipedia.org/wiki/ISO_8601>`_
          time string (not necessarily in exactly the same format);
        - "mixed", to infer the format for each element individually. This is risky,
          and you should probably use it along with `dayfirst`.

        .. versionadded:: 2.0.0
    dayfirst : bool, default False
        DD/MM format dates, international and European format.
    cache_dates : bool, default True
        If ``True``, use a cache of unique, converted dates to apply the ``datetime``
        conversion. May produce significant speed-up when parsing duplicate
        date strings, especially ones with timezone offsets.

    iterator : bool, default False
        Return ``TextFileReader`` object for iteration or getting chunks with
        ``get_chunk()``.
    chunksize : int, optional
        Number of lines to read from the file per chunk. Passing a value will cause the
        function to return a ``TextFileReader`` object for iteration.
        See the `IO Tools docs
        <https://pandas.pydata.org/pandas-docs/stable/io.html#io-chunking>`_
        for more information on ``iterator`` and ``chunksize``.

    compression : str or dict, default 'infer'
        For on-the-fly decompression of on-disk data.
        If 'infer' and 'filepath_or_buffer' is
        path-like, then detect compression from the following extensions: '.gz',
        '.bz2', '.zip', '.xz', '.zst', '.tar', '.tar.gz', '.tar.xz' or '.tar.bz2'
        (otherwise no compression).
        If using 'zip' or 'tar', the ZIP file must contain only
        one data file to be read in.
        Set to ``None`` for no decompression.
        Can also be a dict with key ``'method'`` set
        to one of {``'zip'``, ``'gzip'``, ``'bz2'``,
        ``'zstd'``, ``'xz'``, ``'tar'``} and
        other key-value pairs are forwarded to
        ``zipfile.ZipFile``, ``gzip.GzipFile``,
        ``bz2.BZ2File``, ``zstandard.ZstdDecompressor``, ``lzma.LZMAFile`` or
        ``tarfile.TarFile``, respectively.
        As an example, the following could be passed for
        Zstandard decompression using a
        custom compression dictionary:
        ``compression={'method': 'zstd', 'dict_data': my_compression_dict}``.

    thousands : str (length 1), optional
        Character acting as the thousands separator in numerical values.
    decimal : str (length 1), default '.'
        Character to recognize as decimal point (e.g., use ',' for European data).
    lineterminator : str (length 1), optional
        Character used to denote a line break. Only valid with C parser.
    quotechar : str (length 1), optional
        Character used to denote the start and end of a quoted item. Quoted
        items can include the ``delimiter`` and it will be ignored.
    quoting : {{0 or csv.QUOTE_MINIMAL, 1 or csv.QUOTE_ALL,
        2 or csv.QUOTE_NONNUMERIC, 3 or csv.QUOTE_NONE}}, default csv.QUOTE_MINIMAL
        Control field quoting behavior per ``csv.QUOTE_*`` constants. Default is
        ``csv.QUOTE_MINIMAL`` (i.e., 0) which implies that
        only fields containing special
        characters are quoted (e.g., characters defined
        in ``quotechar``, ``delimiter``,
        or ``lineterminator``.
    doublequote : bool, default True
        When ``quotechar`` is specified and ``quoting`` is not ``QUOTE_NONE``, indicate
        whether or not to interpret two consecutive ``quotechar`` elements INSIDE a
        field as a single ``quotechar`` element.
    escapechar : str (length 1), optional
        Character used to escape other characters.
    comment : str (length 1), optional
        Character indicating that the remainder of line should not be parsed.
        If found at the beginning
        of a line, the line will be ignored altogether. This parameter must be a
        single character. Like empty lines (as long as ``skip_blank_lines=True``),
        fully commented lines are ignored by the parameter ``header`` but not by
        ``skiprows``. For example, if ``comment='#'``, parsing
        ``#empty\na,b,c\n1,2,3`` with ``header=0`` will result in ``'a,b,c'`` being
        treated as the header.
    encoding : str, optional, default 'utf-8'
        Encoding to use for UTF when reading/writing (ex. ``'utf-8'``). `List of Python
        standard encodings
        <https://docs.python.org/3/library/codecs.html#standard-encodings>`_ .

    encoding_errors : str, optional, default 'strict'
        How encoding errors are treated. `List of possible values
        <https://docs.python.org/3/library/codecs.html#error-handlers>`_ .

    dialect : str or csv.Dialect, optional
        If provided, this parameter will override values (default or not) for the
        following parameters: ``delimiter``, ``doublequote``, ``escapechar``,
        ``skipinitialspace``, ``quotechar``, and ``quoting``. If it is necessary to
        override values, a ``ParserWarning`` will be issued. See ``csv.Dialect``
        documentation for more details.
    on_bad_lines : {{'error', 'warn', 'skip'}} or Callable, default 'error'
        Specifies what to do upon encountering a bad line (a line with too many fields).
        Allowed values are:

        - ``'error'``, raise an Exception when a bad line is encountered.
        - ``'warn'``, raise a warning when a bad line is
          encountered and skip that line.
        - ``'skip'``, skip bad lines without raising or warning when
          they are encountered.
        - Callable, function that will process a single bad line.
            - With ``engine='python'``, function with signature
              ``(bad_line: list[str]) -> list[str] | None``.
              ``bad_line`` is a list of strings split by the ``sep``.
              If the function returns ``None``, the bad line will be ignored.
              If the function returns a new ``list`` of strings with
              more elements than
              expected, a ``ParserWarning`` will be emitted while
              dropping extra elements.
            - With ``engine='pyarrow'``, function with signature
              as described in pyarrow documentation: `invalid_row_handler
              <https://arrow.apache.org/docs/python
              /generated/pyarrow.csv.ParseOptions.html
              #pyarrow.csv.ParseOptions.invalid_row_handler>`_.

        .. versionchanged:: 2.2.0

            Callable for ``engine='pyarrow'``

    low_memory : bool, default True
        Internally process the file in chunks, resulting in lower memory use
        while parsing, but possibly mixed type inference.  To ensure no mixed
        types either set ``False``, or specify the type with the ``dtype`` parameter.
        Note that the entire file is read into a single :class:`~pandas.DataFrame`
        regardless, use the ``chunksize`` or ``iterator``
        parameter to return the data in
        chunks. (Only valid with C parser).
    memory_map : bool, default False
        If a filepath is provided for ``filepath_or_buffer``, map the file object
        directly onto memory and access the data directly from there. Using this
        option can improve performance because there is no longer any I/O overhead.
    float_precision : {{'high', 'legacy', 'round_trip'}}, optional

In [4]:
pd.read_csv('sahibindenx.csv')

,searchResultsLargeThumbnail href,s-image src,action href,classifiedTitle,titleIcon href,titleIcon src,searchResultsAttributeValue,searchResultsAttributeValue 2,classified-price-container,searchResultsDateValue,searchResultsDateValue 2,searchResultsLocationValue
0,https://www.sahibinden.com/ilan/emlak-konut-ki...,https://image5.sahibinden.com/primeRow/97/92/8...,https://www.sahibinden.com/kiralik?address_dis...,INVESTPARTNER | GEÇİTPARK EVLERİ KİRALIK 3+1 K...,https://investpartner.sahibinden.com/,https://s0.shbdn.com/assets/images/iconStore@2...,250,3+1,60.000 TL,12 Mart,2026,AtaevlerAhmet Yesevi Mah.
1,https://www.sahibinden.com/ilan/emlak-konut-ki...,https://i0.shbdn.com/photos/86/46/29/lthmb_129...,https://www.sahibinden.com/kiralik?address_dis...,BURSA KUMOVA ADRES BALAT KİRALIK,https://izzettinyorukgayrimenkul.sahibinden.com/,https://s0.shbdn.com/assets/images/iconStore@2...,232,4+1,100.000 TL,10 Mart,2026,AtaevlerAhmet Yesevi Mah.
2,https://www.sahibinden.com/ilan/emlak-konut-ki...,https://i0.shbdn.com/photos/83/58/70/lthmb_130...,https://www.sahibinden.com/kiralik?address_dis...,CEMAL EMLAK BURSA NİLÜFER CUMHURİYET MH FULL E...,https://cemal-emlak.sahibinden.com/,https://s0.shbdn.com/assets/images/iconStore@2...,135,3+1,35.000 TL,15 Mart,2026,AtaevlerCumhuriyet Mah.
3,https://www.sahibinden.com/ilan/emlak-konut-ki...,https://i0.shbdn.com/photos/12/25/13/lthmb_129...,https://www.sahibinden.com/kiralik?address_dis...,BEŞEVLER'DE SİTE İÇİ KİRALIK 3+1 ARAKAT PARK'A...,https://himaxgayrimenkul.sahibinden.com/,https://s0.shbdn.com/assets/images/iconStore@2...,160,3+1,24.500 TL,15 Mart,2026,BeşevlerBeşevler Mh.
4,https://www.sahibinden.com/ilan/emlak-konut-ki...,https://i0.shbdn.com/photos/43/68/23/lthmb_130...,https://www.sahibinden.com/kiralik?address_dis...,NİLÜFER ATAEVLER YÜKSELENPARK ÖZLEM 2 SİTESİ 3...,https://himaxgayrimenkul.sahibinden.com/,https://s0.shbdn.com/assets/images/iconStore@2...,145,3+1,43.000 TL,13 Mart,2026,AtaevlerBarış Mh.
...,...,...,...,...,...,...,...,...,...,...,...,...
935,https://www.sahibinden.com/ilan/emlak-konut-ki...,https://i0.shbdn.com/photos/86/80/10/lthmb_127...,https://www.sahibinden.com/kiralik?pagingOffse...,NİLÜFER HARMONY TOWERS 1+1 KİRALIK EŞYALI DAİRE,https://solmazyilmazgayrimenkul.sahibinden.com/,https://s0.shbdn.com/assets/images/iconStore@2...,116,1+1,41.000 TL,21 Şubat,2026,BeşevlerOdunluk Mah.
936,https://www.sahibinden.com/ilan/emlak-konut-ki...,NaN,https://www.sahibinden.com/kiralik?pagingOffse...,SAHİBİNDEN BURSA BEŞEVLER KİRALIK 3+1 DAİRE,NaN,NaN,125,3+1,20.000 TL,28 Ocak,2026,BeşevlerBeşevler Mh.
937,https://www.sahibinden.com/ilan/emlak-konut-ki...,NaN,https://www.sahibinden.com/kiralik?pagingOffse...,KİRALIK DAİRE,NaN,NaN,95,2+1,17.000 TL,23 Ocak,2026,BeşevlerKültür Mh.
938,https://www.sahibinden.com/ilan/emlak-konut-ki...,NaN,https://www.sahibinden.com/kiralik?pagingOffse...,BURSA NİLÜFER FETHİYE MAH. 3+1 EŞYALI KİRALIK ...,NaN,NaN,130,3+1,25.000 TL,08 Ocak,2026,AtaevlerFethiye Mah.
939,https://www.sahibinden.com/ilan/emlak-konut-ki...,https://i0.shbdn.com/photos/33/13/78/lthmb_126...,https://www.sahibinden.com/kiralik?pagingOffse...,NİLÜFER HARMONY TOWERS Eşyalı daire,NaN,NaN,250,3+1,75.000 TL,12 Eylül,2025,BeşevlerOdunluk Mah.

In [5]:
import pandas as pd
df = pd.read_csv('./sahibindenx.csv')
print(df.head())

                    searchResultsLargeThumbnail href  \
0  https://www.sahibinden.com/ilan/emlak-konut-ki...
1  https://www.sahibinden.com/ilan/emlak-konut-ki...
2  https://www.sahibinden.com/ilan/emlak-konut-ki...
3  https://www.sahibinden.com/ilan/emlak-konut-ki...
4  https://www.sahibinden.com/ilan/emlak-konut-ki...

                                         s-image src  \
0  https://image5.sahibinden.com/primeRow/97/92/8...
1  https://i0.shbdn.com/photos/86/46/29/lthmb_129...
2  https://i0.shbdn.com/photos/83/58/70/lthmb_130...
3  https://i0.shbdn.com/photos/12/25/13/lthmb_129...
4  https://i0.shbdn.com/photos/43/68/23/lthmb_130...

                                         action href  \
0  https://www.sahibinden.com/kiralik?address_dis...
1  https://www.sahibinden.com/kiralik?address_dis...
2  https://www.sahibinden.com/kiralik?address_dis...
3  https://www.sahibinden.com/kiralik?address_dis...
4  https://www.sahibinden.com/kiralik?address_dis...

                                     classifiedTitle  \
0  INVESTPARTNER | GEÇİTPARK EVLERİ KİRALIK 3+1 K...
1                   BURSA KUMOVA ADRES BALAT KİRALIK
2  CEMAL EMLAK BURSA NİLÜFER CUMHURİYET MH FULL E...
3  BEŞEVLER'DE SİTE İÇİ KİRALIK 3+1 ARAKAT PARK'A...
4  NİLÜFER ATAEVLER YÜKSELENPARK ÖZLEM 2 SİTESİ 3...

                                     titleIcon href  \
0             https://investpartner.sahibinden.com/
1  https://izzettinyorukgayrimenkul.sahibinden.com/
2               https://cemal-emlak.sahibinden.com/
3          https://himaxgayrimenkul.sahibinden.com/
4          https://himaxgayrimenkul.sahibinden.com/

                                       titleIcon src  \
0  https://s0.shbdn.com/assets/images/iconStore@2...
1  https://s0.shbdn.com/assets/images/iconStore@2...
2  https://s0.shbdn.com/assets/images/iconStore@2...
3  https://s0.shbdn.com/assets/images/iconStore@2...
4  https://s0.shbdn.com/assets/images/iconStore@2...

   searchResultsAttributeValue searchResultsAttributeValue 2  \
0                          250                           3+1
1                          232                           4+1
2                          135                           3+1
3                          160                           3+1
4                          145                           3+1

  classified-price-container searchResultsDateValue  searchResultsDateValue 2  \
0                  60.000 TL                12 Mart                      2026
1                 100.000 TL                10 Mart                      2026
2                  35.000 TL                15 Mart                      2026
3                  24.500 TL                15 Mart                      2026
4                  43.000 TL                13 Mart                      2026

  searchResultsLocationValue
0  AtaevlerAhmet Yesevi Mah.
1  AtaevlerAhmet Yesevi Mah.
2    AtaevlerCumhuriyet Mah.
3       BeşevlerBeşevler Mh.
4          AtaevlerBarış Mh.

In [6]:
import os as os
print("Şu anki klasör:", os.getcwd())
print("Klasördeki dosyalar:", os.listdir())

Şu anki klasör: /home/yusuf/pyhton_dersleri
Klasördeki dosyalar: ['sahibindenx.csv', 'ders1.py', '.venv', 'verileri_ayikla.ipynb', 'veriler', 'final.csv', 'sahibinden.csv']

In [7]:
import pandas as pd

# 'data' klasörünün içindeki dosyayı oku
df = pd.read_csv('sahibindenx.csv')

# İlk 5 satırı göstererek her şeyin yolunda olduğunu doğrula
df.head()

,searchResultsLargeThumbnail href,s-image src,action href,classifiedTitle,titleIcon href,titleIcon src,searchResultsAttributeValue,searchResultsAttributeValue 2,classified-price-container,searchResultsDateValue,searchResultsDateValue 2,searchResultsLocationValue
0,https://www.sahibinden.com/ilan/emlak-konut-ki...,https://image5.sahibinden.com/primeRow/97/92/8...,https://www.sahibinden.com/kiralik?address_dis...,INVESTPARTNER | GEÇİTPARK EVLERİ KİRALIK 3+1 K...,https://investpartner.sahibinden.com/,https://s0.shbdn.com/assets/images/iconStore@2...,250,3+1,60.000 TL,12 Mart,2026,AtaevlerAhmet Yesevi Mah.
1,https://www.sahibinden.com/ilan/emlak-konut-ki...,https://i0.shbdn.com/photos/86/46/29/lthmb_129...,https://www.sahibinden.com/kiralik?address_dis...,BURSA KUMOVA ADRES BALAT KİRALIK,https://izzettinyorukgayrimenkul.sahibinden.com/,https://s0.shbdn.com/assets/images/iconStore@2...,232,4+1,100.000 TL,10 Mart,2026,AtaevlerAhmet Yesevi Mah.
2,https://www.sahibinden.com/ilan/emlak-konut-ki...,https://i0.shbdn.com/photos/83/58/70/lthmb_130...,https://www.sahibinden.com/kiralik?address_dis...,CEMAL EMLAK BURSA NİLÜFER CUMHURİYET MH FULL E...,https://cemal-emlak.sahibinden.com/,https://s0.shbdn.com/assets/images/iconStore@2...,135,3+1,35.000 TL,15 Mart,2026,AtaevlerCumhuriyet Mah.
3,https://www.sahibinden.com/ilan/emlak-konut-ki...,https://i0.shbdn.com/photos/12/25/13/lthmb_129...,https://www.sahibinden.com/kiralik?address_dis...,BEŞEVLER'DE SİTE İÇİ KİRALIK 3+1 ARAKAT PARK'A...,https://himaxgayrimenkul.sahibinden.com/,https://s0.shbdn.com/assets/images/iconStore@2...,160,3+1,24.500 TL,15 Mart,2026,BeşevlerBeşevler Mh.
4,https://www.sahibinden.com/ilan/emlak-konut-ki...,https://i0.shbdn.com/photos/43/68/23/lthmb_130...,https://www.sahibinden.com/kiralik?address_dis...,NİLÜFER ATAEVLER YÜKSELENPARK ÖZLEM 2 SİTESİ 3...,https://himaxgayrimenkul.sahibinden.com/,https://s0.shbdn.com/assets/images/iconStore@2...,145,3+1,43.000 TL,13 Mart,2026,AtaevlerBarış Mh.

In [8]:
print(df)

                      searchResultsLargeThumbnail href  \
0    https://www.sahibinden.com/ilan/emlak-konut-ki...
1    https://www.sahibinden.com/ilan/emlak-konut-ki...
2    https://www.sahibinden.com/ilan/emlak-konut-ki...
3    https://www.sahibinden.com/ilan/emlak-konut-ki...
4    https://www.sahibinden.com/ilan/emlak-konut-ki...
..                                                 ...
935  https://www.sahibinden.com/ilan/emlak-konut-ki...
936  https://www.sahibinden.com/ilan/emlak-konut-ki...
937  https://www.sahibinden.com/ilan/emlak-konut-ki...
938  https://www.sahibinden.com/ilan/emlak-konut-ki...
939  https://www.sahibinden.com/ilan/emlak-konut-ki...

                                           s-image src  \
0    https://image5.sahibinden.com/primeRow/97/92/8...
1    https://i0.shbdn.com/photos/86/46/29/lthmb_129...
2    https://i0.shbdn.com/photos/83/58/70/lthmb_130...
3    https://i0.shbdn.com/photos/12/25/13/lthmb_129...
4    https://i0.shbdn.com/photos/43/68/23/lthmb_130...
..                                                 ...
935  https://i0.shbdn.com/photos/86/80/10/lthmb_127...
936                                                NaN
937                                                NaN
938                                                NaN
939  https://i0.shbdn.com/photos/33/13/78/lthmb_126...

                                           action href  \
0    https://www.sahibinden.com/kiralik?address_dis...
1    https://www.sahibinden.com/kiralik?address_dis...
2    https://www.sahibinden.com/kiralik?address_dis...
3    https://www.sahibinden.com/kiralik?address_dis...
4    https://www.sahibinden.com/kiralik?address_dis...
..                                                 ...
935  https://www.sahibinden.com/kiralik?pagingOffse...
936  https://www.sahibinden.com/kiralik?pagingOffse...
937  https://www.sahibinden.com/kiralik?pagingOffse...
938  https://www.sahibinden.com/kiralik?pagingOffse...
939  https://www.sahibinden.com/kiralik?pagingOffse...

                                       classifiedTitle  \
0    INVESTPARTNER | GEÇİTPARK EVLERİ KİRALIK 3+1 K...
1                     BURSA KUMOVA ADRES BALAT KİRALIK
2    CEMAL EMLAK BURSA NİLÜFER CUMHURİYET MH FULL E...
3    BEŞEVLER'DE SİTE İÇİ KİRALIK 3+1 ARAKAT PARK'A...
4    NİLÜFER ATAEVLER YÜKSELENPARK ÖZLEM 2 SİTESİ 3...
..                                                 ...
935    NİLÜFER HARMONY TOWERS 1+1 KİRALIK EŞYALI DAİRE
936        SAHİBİNDEN BURSA BEŞEVLER KİRALIK 3+1 DAİRE
937                                      KİRALIK DAİRE
938  BURSA NİLÜFER FETHİYE MAH. 3+1 EŞYALI KİRALIK ...
939                NİLÜFER HARMONY TOWERS Eşyalı daire

                                       titleIcon href  \
0               https://investpartner.sahibinden.com/
1    https://izzettinyorukgayrimenkul.sahibinden.com/
2                 https://cemal-emlak.sahibinden.com/
3            https://himaxgayrimenkul.sahibinden.com/
4            https://himaxgayrimenkul.sahibinden.com/
..                                                ...
935   https://solmazyilmazgayrimenkul.sahibinden.com/
936                                               NaN
937                                               NaN
938                                               NaN
939                                               NaN

                                         titleIcon src  \
0    https://s0.shbdn.com/assets/images/iconStore@2...
1    https://s0.shbdn.com/assets/images/iconStore@2...
2    https://s0.shbdn.com/assets/images/iconStore@2...
3    https://s0.shbdn.com/assets/images/iconStore@2...
4    https://s0.shbdn.com/assets/images/iconStore@2...
..                                                 ...
935  https://s0.shbdn.com/assets/images/iconStore@2...
936                                                NaN
937                                                NaN
938                                                NaN
939                                                NaN

     searchResultsAttributeValue searchResultsAttributeValue 2  \
0                            250                           3+1
1                            232                           4+1
2                            135                           3+1
3                            160                           3+1
4                            145                           3+1
..                           ...                           ...
935                          116                           1+1
936                          125                           3+1
937                           95                           2+1
938                          130                           3+1
939                          250                           3+1

    classified-price-container searchResultsDateValue  \
0                    60.000 TL                12 Mart
1                   100.000 TL                10 Mart
2                    35.000 TL                15 Mart
3                    24.500 TL                15 Mart
4                    43.000 TL                13 Mart
..                         ...                    ...
935                  41.000 TL               21 Şubat
936                  20.000 TL                28 Ocak
937                  17.000 TL                23 Ocak
938                  25.000 TL                08 Ocak
939                  75.000 TL               12 Eylül

     searchResultsDateValue 2 searchResultsLocationValue
0                        2026  AtaevlerAhmet Yesevi Mah.
1                        2026  AtaevlerAhmet Yesevi Mah.
2                        2026    AtaevlerCumhuriyet Mah.
3                        2026       BeşevlerBeşevler Mh.
4                        2026          AtaevlerBarış Mh.
..                        ...                        ...
935                      2026       BeşevlerOdunluk Mah.
936                      2026       BeşevlerBeşevler Mh.
937                      2026         BeşevlerKültür Mh.
938                      2026       AtaevlerFethiye Mah.
939                      2025       BeşevlerOdunluk Mah.

[940 rows x 12 columns]

In [9]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 940 entries, 0 to 939
Data columns (total 12 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   searchResultsLargeThumbnail href  940 non-null    str
 1   s-image src                       899 non-null    str
 2   action href                       940 non-null    str
 3   classifiedTitle                   940 non-null    str
 4   titleIcon href                    861 non-null    str
 5   titleIcon src                     861 non-null    str
 6   searchResultsAttributeValue       940 non-null    int64
 7   searchResultsAttributeValue 2     940 non-null    str
 8   classified-price-container        940 non-null    str
 9   searchResultsDateValue            940 non-null    str
 10  searchResultsDateValue 2          940 non-null    int64
 11  searchResultsLocationValue        940 non-null    str
dtypes: int64(2), str(10)
memory usage: 88.3 KB
None

In [10]:
print(df.head)

<bound method NDFrame.head of                       searchResultsLargeThumbnail href  \
0    https://www.sahibinden.com/ilan/emlak-konut-ki...
1    https://www.sahibinden.com/ilan/emlak-konut-ki...
2    https://www.sahibinden.com/ilan/emlak-konut-ki...
3    https://www.sahibinden.com/ilan/emlak-konut-ki...
4    https://www.sahibinden.com/ilan/emlak-konut-ki...
..                                                 ...
935  https://www.sahibinden.com/ilan/emlak-konut-ki...
936  https://www.sahibinden.com/ilan/emlak-konut-ki...
937  https://www.sahibinden.com/ilan/emlak-konut-ki...
938  https://www.sahibinden.com/ilan/emlak-konut-ki...
939  https://www.sahibinden.com/ilan/emlak-konut-ki...

                                           s-image src  \
0    https://image5.sahibinden.com/primeRow/97/92/8...
1    https://i0.shbdn.com/photos/86/46/29/lthmb_129...
2    https://i0.shbdn.com/photos/83/58/70/lthmb_130...
3    https://i0.shbdn.com/photos/12/25/13/lthmb_129...
4    https://i0.shbdn.com/photos/43/68/23/lthmb_130...
..                                                 ...
935  https://i0.shbdn.com/photos/86/80/10/lthmb_127...
936                                                NaN
937                                                NaN
938                                                NaN
939  https://i0.shbdn.com/photos/33/13/78/lthmb_126...

                                           action href  \
0    https://www.sahibinden.com/kiralik?address_dis...
1    https://www.sahibinden.com/kiralik?address_dis...
2    https://www.sahibinden.com/kiralik?address_dis...
3    https://www.sahibinden.com/kiralik?address_dis...
4    https://www.sahibinden.com/kiralik?address_dis...
..                                                 ...
935  https://www.sahibinden.com/kiralik?pagingOffse...
936  https://www.sahibinden.com/kiralik?pagingOffse...
937  https://www.sahibinden.com/kiralik?pagingOffse...
938  https://www.sahibinden.com/kiralik?pagingOffse...
939  https://www.sahibinden.com/kiralik?pagingOffse...

                                       classifiedTitle  \
0    INVESTPARTNER | GEÇİTPARK EVLERİ KİRALIK 3+1 K...
1                     BURSA KUMOVA ADRES BALAT KİRALIK
2    CEMAL EMLAK BURSA NİLÜFER CUMHURİYET MH FULL E...
3    BEŞEVLER'DE SİTE İÇİ KİRALIK 3+1 ARAKAT PARK'A...
4    NİLÜFER ATAEVLER YÜKSELENPARK ÖZLEM 2 SİTESİ 3...
..                                                 ...
935    NİLÜFER HARMONY TOWERS 1+1 KİRALIK EŞYALI DAİRE
936        SAHİBİNDEN BURSA BEŞEVLER KİRALIK 3+1 DAİRE
937                                      KİRALIK DAİRE
938  BURSA NİLÜFER FETHİYE MAH. 3+1 EŞYALI KİRALIK ...
939                NİLÜFER HARMONY TOWERS Eşyalı daire

                                       titleIcon href  \
0               https://investpartner.sahibinden.com/
1    https://izzettinyorukgayrimenkul.sahibinden.com/
2                 https://cemal-emlak.sahibinden.com/
3            https://himaxgayrimenkul.sahibinden.com/
4            https://himaxgayrimenkul.sahibinden.com/
..                                                ...
935   https://solmazyilmazgayrimenkul.sahibinden.com/
936                                               NaN
937                                               NaN
938                                               NaN
939                                               NaN

                                         titleIcon src  \
0    https://s0.shbdn.com/assets/images/iconStore@2...
1    https://s0.shbdn.com/assets/images/iconStore@2...
2    https://s0.shbdn.com/assets/images/iconStore@2...
3    https://s0.shbdn.com/assets/images/iconStore@2...
4    https://s0.shbdn.com/assets/images/iconStore@2...
..                                                 ...
935  https://s0.shbdn.com/assets/images/iconStore@2...
936                                                NaN
937                                                NaN
938                                                NaN
939                                                NaN

     searchResultsAttributeValue searchResultsAttributeValue 2  \
0                            250                           3+1
1                            232                           4+1
2                            135                           3+1
3                            160                           3+1
4                            145                           3+1
..                           ...                           ...
935                          116                           1+1
936                          125                           3+1
937                           95                           2+1
938                          130                           3+1
939                          250                           3+1

    classified-price-container searchResultsDateValue  \
0                    60.000 TL                12 Mart
1                   100.000 TL                10 Mart
2                    35.000 TL                15 Mart
3                    24.500 TL                15 Mart
4                    43.000 TL                13 Mart
..                         ...                    ...
935                  41.000 TL               21 Şubat
936                  20.000 TL                28 Ocak
937                  17.000 TL                23 Ocak
938                  25.000 TL                08 Ocak
939                  75.000 TL               12 Eylül

     searchResultsDateValue 2 searchResultsLocationValue
0                        2026  AtaevlerAhmet Yesevi Mah.
1                        2026  AtaevlerAhmet Yesevi Mah.
2                        2026    AtaevlerCumhuriyet Mah.
3                        2026       BeşevlerBeşevler Mh.
4                        2026          AtaevlerBarış Mh.
..                        ...                        ...
935                      2026       BeşevlerOdunluk Mah.
936                      2026       BeşevlerBeşevler Mh.
937                      2026         BeşevlerKültür Mh.
938                      2026       AtaevlerFethiye Mah.
939                      2025       BeşevlerOdunluk Mah.

[940 rows x 12 columns]>

In [11]:
print(df.sample(50))

                      searchResultsLargeThumbnail href  \
714  https://www.sahibinden.com/ilan/emlak-konut-ki...
68   https://www.sahibinden.com/ilan/emlak-konut-ki...
116  https://www.sahibinden.com/ilan/emlak-konut-ki...
625  https://www.sahibinden.com/ilan/emlak-konut-ki...
375  https://www.sahibinden.com/ilan/emlak-konut-ki...
22   https://www.sahibinden.com/ilan/emlak-konut-ki...
816  https://www.sahibinden.com/ilan/emlak-konut-ki...
127  https://www.sahibinden.com/ilan/emlak-konut-ki...
189  https://www.sahibinden.com/ilan/emlak-konut-ki...
562  https://www.sahibinden.com/ilan/emlak-konut-ki...
851  https://www.sahibinden.com/ilan/emlak-konut-ki...
197  https://www.sahibinden.com/ilan/emlak-konut-ki...
903  https://www.sahibinden.com/ilan/emlak-konut-ki...
800  https://www.sahibinden.com/ilan/emlak-konut-ki...
896  https://www.sahibinden.com/ilan/emlak-konut-ki...
53   https://www.sahibinden.com/ilan/emlak-konut-ki...
576  https://www.sahibinden.com/ilan/emlak-konut-ki...
234  https://www.sahibinden.com/ilan/emlak-konut-ki...
57   https://www.sahibinden.com/ilan/emlak-konut-ki...
637  https://www.sahibinden.com/ilan/emlak-konut-ki...
515  https://www.sahibinden.com/ilan/emlak-konut-ki...
381  https://www.sahibinden.com/ilan/emlak-konut-ki...
270  https://www.sahibinden.com/ilan/emlak-konut-ki...
60   https://www.sahibinden.com/ilan/emlak-konut-ki...
705  https://www.sahibinden.com/ilan/emlak-konut-ki...
281  https://www.sahibinden.com/ilan/emlak-konut-ki...
147  https://www.sahibinden.com/ilan/emlak-konut-ki...
863  https://www.sahibinden.com/ilan/emlak-konut-ki...
665  https://www.sahibinden.com/ilan/emlak-konut-ki...
133  https://www.sahibinden.com/ilan/emlak-konut-ki...
248  https://www.sahibinden.com/ilan/emlak-konut-ki...
852  https://www.sahibinden.com/ilan/emlak-konut-ki...
143  https://www.sahibinden.com/ilan/emlak-konut-ki...
584  https://www.sahibinden.com/ilan/emlak-konut-ki...
616  https://www.sahibinden.com/ilan/emlak-konut-ki...
426  https://www.sahibinden.com/ilan/emlak-konut-ki...
353  https://www.sahibinden.com/ilan/emlak-konut-ki...
750  https://www.sahibinden.com/ilan/emlak-konut-ki...
837  https://www.sahibinden.com/ilan/emlak-konut-ki...
77   https://www.sahibinden.com/ilan/emlak-konut-ki...
469  https://www.sahibinden.com/ilan/emlak-konut-ki...
690  https://www.sahibinden.com/ilan/emlak-konut-ki...
596  https://www.sahibinden.com/ilan/emlak-konut-ki...
848  https://www.sahibinden.com/ilan/emlak-konut-ki...
602  https://www.sahibinden.com/ilan/emlak-konut-ki...
58   https://www.sahibinden.com/ilan/emlak-konut-ki...
685  https://www.sahibinden.com/ilan/emlak-konut-ki...
504  https://www.sahibinden.com/ilan/emlak-konut-ki...
859  https://www.sahibinden.com/ilan/emlak-konut-ki...
510  https://www.sahibinden.com/ilan/emlak-konut-ki...

                                           s-image src  \
714  https://i0.shbdn.com/photos/51/21/12/lthmb_129...
68   https://i0.shbdn.com/photos/12/95/46/lthmb_129...
116  https://i0.shbdn.com/photos/20/92/90/lthmb_130...
625  https://i0.shbdn.com/photos/51/81/41/lthmb_129...
375  https://i0.shbdn.com/photos/80/60/30/lthmb_130...
22   https://i0.shbdn.com/photos/67/52/50/lthmb_130...
816  https://i0.shbdn.com/photos/41/01/70/lthmb_129...
127  https://i0.shbdn.com/photos/16/45/82/lthmb_130...
189  https://i0.shbdn.com/photos/13/75/13/lthmb_129...
562  https://i0.shbdn.com/photos/16/72/16/lthmb_129...
851  https://i0.shbdn.com/photos/10/95/82/lthmb_130...
197  https://i0.shbdn.com/photos/71/49/21/lthmb_130...
903  https://i0.shbdn.com/photos/83/57/94/lthmb_130...
800  https://i0.shbdn.com/photos/53/06/28/lthmb_129...
896  https://i0.shbdn.com/photos/72/45/38/lthmb_130...
53   https://i0.shbdn.com/photos/76/47/84/lthmb_130...
576  https://i0.shbdn.com/photos/19/55/16/lthmb_129...
234  https://i0.shbdn.com/photos/52/66/12/lthmb_130...
57   https://i0.shbdn.com/photos/49/97/89/lthmb_130...
637  https://i0.shbdn.com/photos/00/03/96/lthmb_129...
515  https://i0.shbdn.com/photos/49/72/37/lthmb_128...
381  https://i0.shbdn.com/photos/16/72/16/lthmb_122...
270  https://i0.shbdn.com/photos/59/92/74/lthmb_129...
60   https://i0.shbdn.com/photos/23/24/71/lthmb_118...
705  https://i0.shbdn.com/photos/00/74/66/lthmb_130...
281  https://i0.shbdn.com/photos/28/72/41/lthmb_127...
147  https://i0.shbdn.com/photos/01/88/75/lthmb_130...
863  https://i0.shbdn.com/photos/05/62/64/lthmb_130...
665  https://i0.shbdn.com/photos/32/10/28/lthmb_130...
133  https://i0.shbdn.com/photos/17/92/28/lthmb_129...
248  https://i0.shbdn.com/photos/84/19/98/lthmb_129...
852  https://i0.shbdn.com/photos/02/96/30/lthmb_129...
143  https://i0.shbdn.com/photos/04/22/52/lthmb_130...
584  https://i0.shbdn.com/photos/98/16/58/lthmb_130...
616  https://i0.shbdn.com/photos/59/87/53/lthmb_130...
426  https://i0.shbdn.com/photos/71/93/25/lthmb_130...
353  https://i0.shbdn.com/photos/90/53/98/lthmb_130...
750  https://i0.shbdn.com/photos/29/42/03/lthmb_129...
837  https://i0.shbdn.com/photos/14/91/78/lthmb_129...
77   https://i0.shbdn.com/photos/10/03/00/lthmb_129...
469  https://i0.shbdn.com/photos/47/41/54/lthmb_130...
690  https://i0.shbdn.com/photos/80/05/24/lthmb_129...
596  https://i0.shbdn.com/photos/66/10/11/lthmb_130...
848  https://i0.shbdn.com/photos/68/31/21/lthmb_129...
602  https://i0.shbdn.com/photos/64/95/11/lthmb_130...
58   https://i0.shbdn.com/photos/09/35/68/lthmb_129...
685  https://i0.shbdn.com/photos/14/75/81/lthmb_130...
504  https://i0.shbdn.com/photos/10/10/70/lthmb_130...
859  https://i0.shbdn.com/photos/78/38/96/lthmb_125...
510  https://i0.shbdn.com/photos/77/02/11/lthmb_129...

                                           action href  \
714  https://www.sahibinden.com/kiralik?pagingOffse...
68   https://www.sahibinden.com/kiralik?pagingOffse...
116  https://www.sahibinden.com/kiralik?pagingOffse...
625  https://www.sahibinden.com/kiralik?pagingOffse...
375  https://www.sahibinden.com/kiralik?pagingOffse...
22   https://www.sahibinden.com/kiralik?pagingOffse...
816  https://www.sahibinden.com/kiralik?pagingOffse...
127  https://www.sahibinden.com/kiralik?pagingOffse...
189  https://www.sahibinden.com/kiralik?pagingSize=...
562  https://www.sahibinden.com/kiralik?pagingOffse...
851  https://www.sahibinden.com/kiralik?pagingOffse...
197  https://www.sahibinden.com/kiralik?pagingSize=...
903  https://www.sahibinden.com/kiralik?pagingOffse...
800  https://www.sahibinden.com/kiralik?pagingOffse...
896  https://www.sahibinden.com/kiralik?pagingOffse...
53   https://www.sahibinden.com/kiralik?pagingOffse...
576  https://www.sahibinden.com/kiralik?pagingOffse...
234  https://www.sahibinden.com/kiralik?pagingOffse...
57   https://www.sahibinden.com/kiralik?pagingOffse...
637  https://www.sahibinden.com/kiralik?pagingOffse...
515  https://www.sahibinden.com/kiralik?pagingOffse...
381  https://www.sahibinden.com/kiralik?pagingOffse...
270  https://www.sahibinden.com/kiralik?pagingOffse...
60   https://www.sahibinden.com/kiralik?pagingOffse...
705  https://www.sahibinden.com/kiralik?pagingOffse...
281  https://www.sahibinden.com/kiralik?pagingOffse...
147  https://www.sahibinden.com/kiralik?pagingOffse...
863  https://www.sahibinden.com/kiralik?pagingOffse...
665  https://www.sahibinden.com/kiralik?pagingOffse...
133  https://www.sahibinden.com/kiralik?pagingOffse...
248  https://www.sahibinden.com/kiralik?pagingOffse...
852  https://www.sahibinden.com/kiralik?pagingOffse...
143  https://www.sahibinden.com/kiralik?pagingOffse...
584  https://www.sahibinden.com/kiralik?pagingOffse...
616  https://www.sahibinden.com/kiralik?pagingOffse...
426  https://www.sahibinden.com/kiralik?pagingOffse...
353  https://www.sahibinden.com/kiralik?pagingOffse...
750  https://www.sahibinden.com/kiralik?pagingOffse...
837  https://www.sahibinden.com/kiralik?pagingOffse...
77   https://www.sahibinden.com/kiralik?pagingOffse...
469  https://www.sahibinden.com/kiralik?pagingOffse...
690  https://www.sahibinden.com/kiralik?pagingOffse...
596  https://www.sahibinden.com/kiralik?pagingOffse...
848  https://www.sahibinden.com/kiralik?pagingOffse...
602  https://www.sahibinden.com/kiralik?pagingOffse...
58   https://www.sahibinden.com/kiralik?pagingOffse...
685  https://www.sahibinden.com/kiralik?pagingOffse...
504  https://www.sahibinden.com/kiralik?pagingOffse...
859  https://www.sahibinden.com/kiralik?pagingOffse...
510  https://www.sahibinden.com/kiralik?pagingOffse...

                                       classifiedTitle  \
714     Balat Ergin Reserve'de KİRALIK 2+1 Geniş Daire
68   BİLİCİ denBALATTA KOÇAKKENT 2 de KİRALIK 2+1 A...
116  BALAT DİKENCİK METEOR EVLER DE KİRALIK DUBLEKS...
625                        FSM BULVARI ARA KAT HAVUZLU
375                       ÇAMLICA DA KİRALIK 2+1 DAİRE
22                    Balat'ta Kiralık Geniş 4+1 Daire
816  KİRALIK ÇATI KATI DAİRE/ ELEKTİRİK-S­U-DOĞALGA...
127  RW UYGAR"DAN BEŞEVLER BİLGİNLER CAD.KİRALIK DAİRE
189  YGO'DAN BEŞEVLER KONAK MERKEZDE METRO'YA YAKIN...
562  FSM-Podyum park arası**EŞYALI**3+1 Konforlu-Ot...
851  BURSA CENTRAL BALAT BİTİŞİĞİ KİRALIK LÜX 1+1 D...
197  ÜSTÜNEL'DEN BEŞEVLER'DE 3+1 AİLE TİPİ EŞYASIZ ...
903                          BALATTA kiralık 2+1 daire
800  KİRALIK SIFIR LÜKS DAİRE 3+1 PARK MANZARALI AR...
896  ELFİ DEN BALAT KENT SUİTES 2+1 SIFIR 3. KAT Kİ...
53   NİLÜFER BEŞEVLER KONAK MH KİRALIK 150 m2 LÜX 3...
576  DUNE GYO NİLÜFER BALAT KİRALIK 3+1 ARA KAT BOŞ...
234  Bursa Nilüfer Cumhuriyet Site içi 3+1 Kiralık ...
57       YNG Altın Bursa Nilüfer Odunluk kiralık daire
637  VİZYON16'DAN SÜPER KONUM ATAEVLER METROSU YAKI...
515  DYNAMİC OFFİCE'DEN CUMHURİYET MAH 4+1 KİRALIK ...
381     BURSA NİLÜFER BEŞEVLER DE EŞYALI KİRALIK DAİRE
270  NİLÜFER ODUNLUK PRESTİJ PARK EVLERİ KİRALIK LÜ...
60   NİLÜFER CENTRAL BALAT 1+1 FULL EŞYALI KİRALIK ...
705                ATAEVLERDE KİRALIK 3+1 ARAKAT DAİRE
281  NİLÜFER BEŞEVLER YILDIRIM CADDESİNDE 2+1 KİRAL...
147  NİLÜFER BEŞEVLER CADDESİNDE2+1 METROYA YAKIN G...
863  BEŞEVLER METRO İSTASYONUNA ÇOK YAKIN ARAKAT KO...
665      Beşevler Merkezi 4+1 Modern ve Aydınlık Daire
133  DİALOG SUN BEŞEVLER KÜLTÜR MAHALLESİ KİRALIK 3...
248  Nilüfer Ataevler Metro Yakını Havuzlu Sitede 4...
852  BEŞEVLER KÜLTÜR MAHALLESİ 3+1 SİTE İÇİ GENİŞ A...
143       Nilüfer Fethiye'de Kiralık 5+1 Dubleks Daire
584  ELİF'TEN BEŞEVLER KONAK MAH.CADDE ÜZERİ KİRALI...
616  CB LEVEL'DAN AHMET YESEVİ MAH. ADA SAPPHİRE'DE...
426    Nilüfer Balat Merkez'de 3+1 Kiralık Ferah Daire
353  NİLÜFER KONAK MAHALLESİNDE GENİŞ 3+1 KİRALIK D...
750  BALAT PARK PANORAMADA HAVUZLU SİTEDE 3+1 LÜKS ...
837  Besevler Konak ta kapanmaz manzarali 3+1 Icten...
77                Cumhuriyet Mah. de 3+1 Kiralık Daire
469  Rt Safir Gm den Çamlıcada Uludağ Manzaralı 4+1...
690  FSM Metro'ya Yakın, Site İçinde 3+1 Kiralık Daire
596        BALADIUM RESİDENCE 1+1 EŞYALI KİRALIK DAİRE
848  NEW BALAT | KİRALIK 3+1 158 M² KİRALIK ARA KAT...
602  OFİS ODAK TAN KİRALIK BAKGÖR CİTY 1 DE BAHÇE C...
58     DİMORA CITY 2.ETAP 2+1 KİRALIK DAİRE 134 m2 NET
685  FETHİYE EMİRKENT SİTESİ PODYUM PARK CEPHE ARAK...
504  BAL'DAN ÇELEBİ NOVA SİTESİNDE KİRALIK 3+1 DUBLEKS
859  ELFİ DEN BALAT LUXURY LİFE PROJESİNDE KİRALİK ...
510  C21 EWA'DAN CUMHURİYET MAH DE 3+1 KOMBİLİ ARAK...

                                        titleIcon href  \
714              https://alangoyatirim.sahibinden.com/
68            https://bilicirealestate.sahibinden.com/
116          https://sozerigayrimenkul.sahibinden.com/
625           https://lidergayrimenkul.sahibinden.com/
375                https://fastyatirim.sahibinden.com/
22           https://kwalfagayrimenkul.sahibinden.com/
816       https://denizmavigayrimenkul.sahibinden.com/
127  https://realtyworlduygargayrimenkul.sahibinden...
189      https://yatirimcimgayrimenkul.sahibinden.com/
562                https://dilbayemlak.sahibinden.com/
851                https://citywinners.sahibinden.com/
197    https://ustunelgayrimenkulbursa.sahibinden.com/
903           https://resitalkalebursa.sahibinden.com/
800        https://bayraktaremlakbursa.sahibinden.com/
896            https://elfigayrimenkul.sahibinden.com/
53          https://aydinemlakbesevler.sahibinden.com/
576            https://dunegayrimenkul.sahibinden.com/
234      https://bursadenizgayrimenkul.sahibinden.com/
57         https://yngaltingayrimenkul.sahibinden.com/
637              https://vizyon16group.sahibinden.com/
515              https://dynamicoffice.sahibinden.com/
381            https://yasaremlakofisi.sahibinden.com/
270    https://tasellergrupgayrimenkul.sahibinden.com/
60          https://taskalegayrimenkul.sahibinden.com/
705                 https://brokerteam.sahibinden.com/
281   https://gencbayraktargayrimenkul.sahibinden.com/
147              https://dialogturkiye.sahibinden.com/
863       https://ataemlakgayrimenkull.sahibinden.com/
665               https://century21ewa.sahibinden.com/
133       https://dialogsungayrimenkul.sahibinden.com/
248                https://huseyinbaki.sahibinden.com/
852                                                NaN
143            https://monsgayrimenkul.sahibinden.com/
584       https://elifgayrimenkulbursa.sahibinden.com/
616                         https://16.sahibinden.com/
426          https://rwjivagayrimenkul.sahibinden.com/
353  https://caglayanyatirimgayrimenkul.sahibinden....
750  https://coldwellbankersilvergayrimenkul.sahibi...
837                                                NaN
77         https://emlakvagonuihsaniye.sahibinden.com/
469              https://referanssafir.sahibinden.com/
690                 https://oncu-emlak.sahibinden.com/
596            https://sansgayrimenkul.sahibinden.com/
848                https://homeinbursa.sahibinden.com/
602        https://ofisodakgayrimenkul.sahibinden.com/
58      https://dialogidealgayrimenkul.sahibinden.com/
685       https://harunatesgayrimenkul.sahibinden.com/
504      https://balgayrimenkulyatirim.sahibinden.com/
859            https://elfigayrimenkul.sahibinden.com/
510               https://century21ewa.sahibinden.com/

                                         titleIcon src  \
714  https://s0.shbdn.com/assets/images/iconStore@2...
68   https://s0.shbdn.com/assets/images/iconStore@2...
116  https://s0.shbdn.com/assets/images/iconStore@2...
625  https://s0.shbdn.com/assets/images/iconStore@2...
375  https://s0.shbdn.com/assets/images/iconStore@2...
22   https://s0.shbdn.com/assets/images/iconStore@2...
816  https://s0.shbdn.com/assets/images/iconStore@2...
127  https://s0.shbdn.com/assets/images/iconStore@2...
189  https://s0.shbdn.com/assets/images/iconStore@2...
562  https://s0.shbdn.com/assets/images/iconStore@2...
851  https://s0.shbdn.com/assets/images/iconStore@2...
197  https://s0.shbdn.com/assets/images/iconStore@2...
903  https://s0.shbdn.com/assets/images/iconStore@2...
800  https://s0.shbdn.com/assets/images/iconStore@2...
896  https://s0.shbdn.com/assets/images/iconStore@2...
53   https://s0.shbdn.com/assets/images/iconStore@2...
576  https://s0.shbdn.com/assets/images/iconStore@2...
234  https://s0.shbdn.com/assets/images/iconStore@2...
57   https://s0.shbdn.com/assets/images/iconStore@2...
637  https://s0.shbdn.com/assets/images/iconStore@2...
515  https://s0.shbdn.com/assets/images/iconStore@2...
381  https://s0.shbdn.com/assets/images/iconStore@2...
270  https://s0.shbdn.com/assets/images/iconStore@2...
60   https://s0.shbdn.com/assets/images/iconStore@2...
705  https://s0.shbdn.com/assets/images/iconStore@2...
281  https://s0.shbdn.com/assets/images/iconStore@2...
147  https://s0.shbdn.com/assets/images/iconStore@2...
863  https://s0.shbdn.com/assets/images/iconStore@2...
665  https://s0.shbdn.com/assets/images/iconStore@2...
133  https://s0.shbdn.com/assets/images/iconStore@2...
248  https://s0.shbdn.com/assets/images/iconStore@2...
852                                                NaN
143  https://s0.shbdn.com/assets/images/iconStore@2...
584  https://s0.shbdn.com/assets/images/iconStore@2...
616  https://s0.shbdn.com/assets/images/iconStore@2...
426  https://s0.shbdn.com/assets/images/iconStore@2...
353  https://s0.shbdn.com/assets/images/iconStore@2...
750  https://s0.shbdn.com/assets/images/iconStore@2...
837                                                NaN
77   https://s0.shbdn.com/assets/images/iconStore@2...
469  https://s0.shbdn.com/assets/images/iconStore@2...
690  https://s0.shbdn.com/assets/images/iconStore@2...
596  https://s0.shbdn.com/assets/images/iconStore@2...
848  https://s0.shbdn.com/assets/images/iconStore@2...
602  https://s0.shbdn.com/assets/images/iconStore@2...
58   https://s0.shbdn.com/assets/images/iconStore@2...
685  https://s0.shbdn.com/assets/images/iconStore@2...
504  https://s0.shbdn.com/assets/images/iconStore@2...
859  https://s0.shbdn.com/assets/images/iconStore@2...
510  https://s0.shbdn.com/assets/images/iconStore@2...

     searchResultsAttributeValue searchResultsAttributeValue 2  \
714                          130                           2+1
68                           100                           2+1
116                          373                           4+1
625                          160                           3+1
375                          100                           2+1
22                           240                           4+1
816                          110                           3+1
127                          130                           3+1
189                          130                           2+1
562                          130                           3+1
851                           55                           1+1
197                          125                           3+1
903                          105                           2+1
800                          179                           3+1
896                           65                           2+1
53                           150                           3+1
576                          135                           3+1
234                          160                           3+1
57                           114                           2+1
637                          180                           3+1
515                          180                           4+1
381                           43                           1+1
270                          196                           3+1
60                            70                           1+1
705                          150                           3+1
281                           95                           2+1
147                          110                           2+1
863                          140                           3+1
665                          175                           4+1
133                          145                           3+1
248                          190                           4+1
852                          140                           3+1
143                          175                           5+1
584                          140                           3+1
616                           92                           1+1
426                          145                           3+1
353                          150                           3+1
750                          175                           3+1
837                          180                           3+1
77                           120                           3+1
469                          180                           4+1
690                          150                           3+1
596                           98                           1+1
848                          233                           3+1
602                          220                           4+1
58                           150                           2+1
685                          120                           2+1
504                          160                           3+1

In [12]:
help(df.drop)

Help on method drop in module pandas.core.frame:

drop(labels: 'IndexLabel | ListLike' = None, *, axis: 'Axis' = 0, index: 'IndexLabel | ListLike' = None, columns: 'IndexLabel | ListLike' = None, level: 'Level | None' = None, inplace: 'bool' = False, errors: 'IgnoreRaise' = 'raise') -> 'DataFrame | None' method of pandas.DataFrame instance
    Drop specified labels from rows or columns.

    Remove rows or columns by specifying label names and corresponding
    axis, or by directly specifying index or column names. When using a
    multi-index, labels on different levels can be removed by specifying
    the level. See the :ref:`user guide <advanced.shown_levels>`
    for more information about the now unused levels.

    Parameters
    ----------
    labels : single label or iterable of labels
        Index or column labels to drop. A tuple will be used as a single
        label and not treated as an iterable.
    axis : {0 or 'index', 1 or 'columns'}, default 0
        Whether to drop labels from the index (0 or 'index') or
        columns (1 or 'columns').
    index : single label or iterable of labels
        Alternative to specifying axis (``labels, axis=0``
        is equivalent to ``index=labels``).
    columns : single label or iterable of labels
        Alternative to specifying axis (``labels, axis=1``
        is equivalent to ``columns=labels``).
    level : int or level name, optional
        For MultiIndex, level from which the labels will be removed.
    inplace : bool, default False
        If False, return a copy. Otherwise, do operation
        in place and return None.
    errors : {'ignore', 'raise'}, default 'raise'
        If 'ignore', suppress error and only existing labels are
        dropped.

    Returns
    -------
    DataFrame or None
        Returns DataFrame or None DataFrame with the specified
        index or column labels removed or None if inplace=True.

    Raises
    ------
    KeyError
        If any of the labels is not found in the selected axis.

    See Also
    --------
    DataFrame.loc : Label-location based indexer for selection by label.
    DataFrame.dropna : Return DataFrame with labels on given axis omitted
        where (all or any) data are missing.
    DataFrame.drop_duplicates : Return DataFrame with duplicate rows
        removed, optionally only considering certain columns.
    Series.drop : Return Series with specified index labels removed.

    Examples
    --------
    >>> df = pd.DataFrame(np.arange(12).reshape(3, 4), columns=["A", "B", "C", "D"])
    >>> df
       A  B   C   D
    0  0  1   2   3
    1  4  5   6   7
    2  8  9  10  11

    Drop columns

    >>> df.drop(["B", "C"], axis=1)
       A   D
    0  0   3
    1  4   7
    2  8  11

    >>> df.drop(columns=["B", "C"])
       A   D
    0  0   3
    1  4   7
    2  8  11

    Drop a row by index

    >>> df.drop([0, 1])
       A  B   C   D
    2  8  9  10  11

    Drop columns and/or rows of MultiIndex DataFrame

    >>> midx = pd.MultiIndex(
    ...     levels=[["llama", "cow", "falcon"], ["speed", "weight", "length"]],
    ...     codes=[[0, 0, 0, 1, 1, 1, 2, 2, 2], [0, 1, 2, 0, 1, 2, 0, 1, 2]],
    ... )
    >>> df = pd.DataFrame(
    ...     index=midx,
    ...     columns=["big", "small"],
    ...     data=[
    ...         [45, 30],
    ...         [200, 100],
    ...         [1.5, 1],
    ...         [30, 20],
    ...         [250, 150],
    ...         [1.5, 0.8],
    ...         [320, 250],
    ...         [1, 0.8],
    ...         [0.3, 0.2],
    ...     ],
    ... )
    >>> df
                    big     small
    llama   speed   45.0    30.0
            weight  200.0   100.0
            length  1.5     1.0
    cow     speed   30.0    20.0
            weight  250.0   150.0
            length  1.5     0.8
    falcon  speed   320.0   250.0
            weight  1.0     0.8
            length  0.3     0.2

    Drop a specific index combination from the MultiIndex
    DataFrame, i.e., drop the combination ``'falcon'`` and
    ``'weight'``, which deletes only the corresponding row

    >>> df.drop(index=("falcon", "weight"))
                    big     small
    llama   speed   45.0    30.0
            weight  200.0   100.0
            length  1.5     1.0
    cow     speed   30.0    20.0
            weight  250.0   150.0
            length  1.5     0.8
    falcon  speed   320.0   250.0
            length  0.3     0.2

    >>> df.drop(index="cow", columns="small")
                    big
    llama   speed   45.0
            weight  200.0
            length  1.5
    falcon  speed   320.0
            weight  1.0
            length  0.3

    >>> df.drop(index="length", level=1)
                    big     small
    llama   speed   45.0    30.0
            weight  200.0   100.0
    cow     speed   30.0    20.0
            weight  250.0   150.0
    falcon  speed   320.0   250.0
            weight  1.0     0.8

In [13]:
print(df.columns)

Index(['searchResultsLargeThumbnail href', 's-image src', 'action href',
       'classifiedTitle', 'titleIcon href', 'titleIcon src',
       'searchResultsAttributeValue', 'searchResultsAttributeValue 2',
       'classified-price-container', 'searchResultsDateValue',
       'searchResultsDateValue 2', 'searchResultsLocationValue'],
      dtype='str')

In [14]:
import pandas as pd

# CSV dosyanı okutuyorsun
df = pd.read_csv("sahibindenx.csv")

# Sadece işimize yarayan sütunları seçip yeni bir DataFrame oluşturuyoruz
df_temiz = df[["searchResultsAttributeValue", "searchResultsAttributeValue 2", 
               "classified-price-container", "searchResultsLocationValue"]].copy()

# Sütun isimlerini makul, anlaşılır isimlerle değiştiriyoruz
df_temiz.columns = ["Metrekare", "Oda", "Fiyat", "Konum"]

# Fiyat sütunundaki " TL" yazısını ve binlik ayracı olan "." işaretini siliyoruz
df_temiz["Fiyat"] = df_temiz["Fiyat"].str.replace(" TL", "").str.replace(".", "")

# Fiyatı matematiksel işlem yapılabilmesi için Integer (tam sayı) tipine dönüştürüyoruz
df_temiz["Fiyat"] = df_temiz["Fiyat"].astype(int)

# Temizlenmiş verimizin ilk birkaç satırına bakıyoruz
print(df_temiz.head())

   Metrekare  Oda   Fiyat                      Konum
0        250  3+1   60000  AtaevlerAhmet Yesevi Mah.
1        232  4+1  100000  AtaevlerAhmet Yesevi Mah.
2        135  3+1   35000    AtaevlerCumhuriyet Mah.
3        160  3+1   24500       BeşevlerBeşevler Mh.
4        145  3+1   43000          AtaevlerBarış Mh.

In [15]:
df.isnull().sum()

searchResultsLargeThumbnail href     0
s-image src                         41
action href                          0
classifiedTitle                      0
titleIcon href                      79
titleIcon src                       79
searchResultsAttributeValue          0
searchResultsAttributeValue 2        0
classified-price-container           0
searchResultsDateValue               0
searchResultsDateValue 2             0
searchResultsLocationValue           0
dtype: int64

In [16]:
# Oda sütunundaki "3+1" gibi değerleri toplar (Örn: 4 yapar)
df_temiz['Oda'] = df_temiz['Oda'].apply(lambda x: sum(int(i) for i in str(x).split('+')))

# Mahalle isimlerini ayırma işlemleri için de df_temiz kullanmalısın
df_temiz['Konum'] = df_temiz['Konum'].str.replace("Ataevler", "Ataevler ")
df_temiz['Konum'] = df_temiz['Konum'].str.replace("Beşevler", "Beşevler ")

ValueError: invalid literal for int() with base 10: 'Stüdyo (1'

In [17]:
print(df_temiz['Oda'].unique())

<StringArray>
[         '3+1',          '4+1',          '2+1', 'Stüdyo (1+0)',
          '1+1',          '5+1',          '3+0',          '4+2',
        '3.5+1',          '6+1',          '6+2',        '5.5+1',
        '2.5+1',          '7+2',          '3+2',          '5+2']
Length: 16, dtype: str

In [18]:
# Oda sayısını hesaplayan akıllı bir fonksiyon yazıyoruz
def oda_hesapla(deger):
    deger = str(deger).lower().strip() # Yazıyı küçült ve boşlukları sil
    
    if deger == 'nan':
        return None # Boş verileri None yapıyoruz
    elif 'stüdyo' in deger:
        return 1 # Stüdyo daireler 1 oda sayılır
        
    try:
        # "3+1" formatında olanları topla
        return sum(int(i) for i in deger.split('+'))
    except ValueError:
        # Eğer "10 ve üzeri" gibi hesaplanamayan bir şey gelirse None (boş) yap
        return None

# Yazdığımız bu fonksiyonu Oda sütununa uyguluyoruz
df_temiz['Oda'] = df_temiz['Oda'].apply(oda_hesapla)

# Eğer hesaplanamayan (None olan) ilanlar oluştuysa onları veri setinden siliyoruz
df_temiz = df_temiz.dropna(subset=['Oda'])

# EKLENEN KISIM: Boşluklar silindikten sonra sütunu tam sayı (integer) formatına zorluyoruz
df_temiz['Oda'] = df_temiz['Oda'].astype(int)

In [19]:
print(df_temiz[['Oda', 'Konum']].head(10))

   Oda                      Konum
0    4  AtaevlerAhmet Yesevi Mah.
1    5  AtaevlerAhmet Yesevi Mah.
2    4    AtaevlerCumhuriyet Mah.
3    4       BeşevlerBeşevler Mh.
4    4          AtaevlerBarış Mh.
5    4       BeşevlerBeşevler Mh.
6    3         BeşevlerKonak Mah.
7    4    AtaevlerCumhuriyet Mah.
8    1       AtaevlerFethiye Mah.
9    2       AtaevlerIşıktepe Mh.

In [20]:
# Belde sütununa veriyi çekiyoruz (Bu kısım aynı)
df_temiz['Belde'] = df_temiz['Konum'].str.extract('(Ataevler|Beşevler)')

# Sadece cümlenin en başındaki (^) Ataevler veya Beşevler kelimelerini sileriz
df_temiz['Konum'] = df_temiz['Konum'].str.replace('^(Ataevler|Beşevler)', '', regex=True).str.strip()

In [21]:
print(df_temiz[['Belde', 'Konum']].head(10))

      Belde              Konum
0  Ataevler  Ahmet Yesevi Mah.
1  Ataevler  Ahmet Yesevi Mah.
2  Ataevler    Cumhuriyet Mah.
3  Beşevler       Beşevler Mh.
4  Ataevler          Barış Mh.
5  Beşevler       Beşevler Mh.
6  Beşevler         Konak Mah.
7  Ataevler    Cumhuriyet Mah.
8  Ataevler       Fethiye Mah.
9  Ataevler       Işıktepe Mh.

In [22]:
print(df_temiz.isnull().sum())

Metrekare    0
Oda          0
Fiyat        0
Konum        0
Belde        0
dtype: int64

In [23]:
# Eğer hücrede sadece boşluk karakteri varsa (veya tamamen boşsa) bunu Pandas'ın anlayacağı 'None' (boş değer) formatına çeviriyoruz
df_temiz['Konum'] = df_temiz['Konum'].replace(r'^\s*$', None, regex=True)

# 'Konum' sütununda boş değer (None/NaN) olan tüm satırları veri setinden siliyoruz
df_temiz = df_temiz.dropna(subset=['Konum'])

In [ ]:
df_temiz.to_csv('final.csv', index=False)

In [ ]:
#iş bittii